OrderChina/Controllers/WalletController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using OrderChina.Common;
using OrderChina.Models;
using PagedList;
using System.Reflection;
using System.ComponentModel.DataAnnotations;

namespace OrderChina.Controllers
{
    public class WalletController : Controller
    {
        DBContext db = new DBContext();
        //
        // GET: /Wallet/

        public ActionResult Index(string id, int? page)
        {
            var listUser = db.UserProfiles.ToList();
            var dicUserByPhone = new Dictionary<string, string>();
            foreach (var userProfile in listUser)
                dicUserByPhone[userProfile.Phone] = userProfile.Email;
            ViewBag.DicUser = dicUserByPhone;
            if (Session["UserType"] != null && (Utils.CheckRole((string)Session["UserType"], (int)UserType.Client, false) || Utils.CheckRole((string)Session["UserType"], (int)UserType.Orderer, false)))
            {
                const int pageSize = 50;
                int pageNumber = (page ?? 1);
                var model = new IndexWalletModel { Wallets = db.Wallets.Where(a => a.Client == User.Identity.Name) };

                var listId = model.Wallets.Select(a => a.Id).ToList();
                model.WalletHistorys = db.WalletHistorys.Where(a => listId.Contains(a.WalletId)).ToList()
                    .ToPagedList(pageNumber, pageSize);

                return View(model);
            }
            else if (Session["UserType"] != null && Utils.CheckRole((string)Session["UserType"]))
            {

                ViewBag.isadmin = true;
                ViewBag.phone = id;
                const int pageSize = 50;
                int pageNumber = (page ?? 1);
                var model = new IndexWalletModel { Wallets = db.Wallets.Where(a => a.Client == id) };

                var listId = model.Wallets.Select(a => a.Id).ToList();
                model.WalletHistorys = db.WalletHistorys.Where(a => listId.Contains(a.WalletId)).ToList()
                    .ToPagedList(pageNumber, pageSize);
                return View(model);
            }
            else if (Session["UserType"] != null && Utils.CheckRole((string)Session["UserType"], (int)UserType.Accounting, false))
            {

                ViewBag.isacc = true;
                ViewBag.phone = id;

                const int pageSize = 50;
                int pageNumber = (page ?? 1);
                var model = new IndexWalletModel { Wallets = db.Wallets.Where(a => a.Client == id) };

                var listId = model.Wallets.Select(a => a.Id).ToList();
                model.WalletHistorys = db.WalletHistorys.Where(a => listId.Contains(a.WalletId)).ToList()
                    .ToPagedList(pageNumber, pageSize);

                return View(model);
            }
            return RedirectToAction("Error", "Home");
        }

        public ActionResult CreateWallet(string id)
        {
            var user = db.UserProfiles.FirstOrDefault(a => a.Phone == id);
            var model = new Wallet
            {
                Client = id
            };

            ViewBag.UserType = user != null ? user.UserType : "system";
            ViewBag.ListBankName = GetListBankName(null, "VND");
            ViewBag.ListCurrency = GetListCurrency(id, user);
            ViewBag.ListWalletType = GetListWalletType();

            return PartialView("_CreateWallet", model);
        }

        private SelectList GetListCurrency(string id, UserProfile user)
        {
            List<Object> list = new List<Object>();
            if (user != null)
            {
                if (Utils.CheckRole(user.UserType, (int)UserType.Client, false))
                {
                    var listWallet = db.Wallets.Where(a => a.Client == id).Select(a => a.Currency).ToList();
                    var items =
                        db.Currencys.Where(a => !listWallet.Contains(a.Code) && a.Code == Utils.VND)
                        .Select(a => new { value = a.Code, display = a.Code + " - " + a.Description });
                    foreach (var item in items)
                    {
                        list.Add(item);
                    }

                }
                else if (Utils.CheckRole(user.UserType, (int)UserType.Orderer, false))
                {
                    var itemsOrder =
                        db.Currencys.Where(a => a.Code == Utils.CNY)
                        .Select(a => new { value = a.Code, display = a.Code + " - " + a.Description });
                    foreach (var item in itemsOrder)
                    {
                        list.Add(item);
                    }
                }

            }
            else
            {
                var itemsOrder =
                        db.Currencys.Distinct()
                        .Select(a => new { value = a.Code, display = a.Code + " - " + a.Description });
                foreach (var item in itemsOrder)
                {
                    list.Add(item);
                }
            }

            return new SelectList(list, "value", "display");
        }

        private SelectList GetListWalletType()
        {
            var list = new List<object>();
            foreach (FieldInfo fieldInfo in typeof(WalletType).GetFields())
            {
                if (fieldInfo.FieldType.Name != "WalletType")
                    continue;
                var attribute = Attribute.GetCustomAttribute(fieldInfo,
                    typeof(DisplayAttribute)) as DisplayAttribute;

                if (attribute != null)
                    list.Add(new { name = fieldInfo.Name, display = attribute.Name });
                else
                    list.Add(new { name = fieldInfo.Name, display = fieldInfo.Name });
            }

            return new SelectList(list, "name", "display", "Online");
        }

        private SelectList GetListBankName(string client, string currency)
        {
            var listWallet = string.IsNullOrWhiteSpace(currency) ?
                                                                      db.Wallets.Where(a => a.Client == client).ToList() :
                                                                                                                             db.Wallets.Where(a => a.Client == client && a.Currency == currency).ToList();

            var list = new List<Object>();

            var isEmptyCurrency = string.IsNullOrWhiteSpace(currency);

            foreach (var a in listWallet)
            {
                list.Add(isEmptyCurrency
                             ? new { value = a.Currency + "#" + a.Name + "#" + a.Id, display = a.Currency + " - " + a.Name }
                             : new { value = a.Name, display = a.Name });
            }

            return new SelectList(list, "value", "display");
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult CreateWallet(Wallet model)
        {
            var userInfo = db.UserProfiles.FirstOrDefault(c => c.Phone == model.Client);
            if (userInfo != null)
            {
                // truong hop la tao vi khach hang cong tien ca tai khoan khach hang va tai khoan he thong
                if (userInfo.UserType == ((int)UserType.Client).ToString())
                {
                    if (string.IsNullOrWhiteSpace(model.Name))
                        return RedirectToAction("Index", new { id = model.Client });

                    var accountSystem = GetWallet(null, model.Name);
                    if (accountSystem == null)
                        return RedirectToAction("Index", new { id = model.Client });

                    accountSystem.Money += model.Money;

                    model.User_Update = User.Identity.Name;
                    model.LastUpdate = DateTime.Now;

                    db.Wallets.Add(model);
                    db.SaveChanges();

                    InsertWalletHistory(accountSystem, model.Money, string.Format("Tạo mới ví cho user: {0} số tiền trong ví: {1}", model.Client, model.Money.ToString("N0")));
                    InsertWalletHistory(model, model.Money, string.Format("Tạo mới ví, số tiền trong ví: {0}", model.Money.ToString("N0")));
                    model.Name = string.Empty;

                    db.SaveChanges();

                }
            }
            else
            {
                model.User_Update = User.Identity.Name;
                model.LastUpdate = DateTime.Now;

                db.Wallets.Add(model);
                db.SaveChanges();

                InsertWalletHistory(model, model.Money, string.Format("Tạo mới ví, số tiền trong ví: {0}", model.Money.ToString("N0")));
                db.SaveChanges();

            }



            return RedirectToAction("Index", new { id = model.Client });
        }
        private void InsertWalletHistory(Wallet walletClient, double money, string reason,string note="")
        {
            try
            {
                if (walletClient == null)
                    return;
                var wallerHistory = new WalletHistory
                {
                    WalletId = walletClient.Id,
                    Money = money,
                    UpdateType = money >= 0 ? WalletUpdateType.Addition.ToString() : WalletUpdateType.Subtract.ToString(),
                    Client = walletClient.Client,
                    Currency = walletClient.Currency,
                    User_Update = User.Identity.Name,
                    LastUpdate = DateTime.Now,
                    Reason = reason,
                    Note = note
                };
                db.WalletHistorys.Add(wallerHistory);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }

        public ActionResult AdditionWallet(int id, string cmd)
        {
            ViewBag.isaddition = cmd == "add";

OrderChina/Views/Wallet/Index.cshtml
@{
    ViewBag.Title = "Index";
}
@using OrderChina.Models
@using PagedList.Mvc
@model IndexWalletModel
@using OrderChina.Common
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@if (Session["UserType"] != null)
{

    if (Utils.CheckRole((string)Session["UserType"], (int)UserType.Client, false))
    { @Html.Partial("_Menu_User_Horizontal")}
}
<section @*class='container'*@ style='padding: 15px;'>
    <div class='row'>

        @if (Utils.CheckRole((string)Session["UserType"], (int)UserType.Client, false))
        {
            @(ViewBag.isadmin != null ?
            Html.Partial("_LayoutUser", new ViewDataDictionary { { "walletmanage", true } }) :
            ViewBag.isacc != null ? Html.Partial("_LayoutUser", new ViewDataDictionary { { "walletmanage", true } }) : Html.Partial("_LayoutUser", new ViewDataDictionary { { "wallet", true } }))
        }
        else
        {
            @(ViewBag.isadmin != null ?
            Html.Partial("_AsideMenuPartial", new ViewDataDictionary { { "walletmanage", true } }) :
            ViewBag.isacc != null ? Html.Partial("_AsideMenuPartial", new ViewDataDictionary { { "walletmanage", true } }) : Html.Partial("_AsideMenuPartial", new ViewDataDictionary { { "wallet", true } }))
        }
        <div class="col-md-9 order-content">
            @if (ViewBag.isadmin != null)
            {
                <a rel='tooltip' title="Tạo mới ví"
                   href=@Url.Action("CreateWallet", "Wallet", new { id = ViewBag.phone }) class="btn btn-xs btn-primary btn-create">
                    <i class="fa fa-file"></i>
                    Tạo mới ví
                </a>
            }

            <ul class="my-row">
                @foreach (var item in Model.Wallets)
                {
                    <li>
                        <i class="fa fa-money">@item.Currency</i>
                        <div class="content-container">
                            <span class="name">Tên ngân hàng: @item.Name</span>
                        </div>
                        <div class="content-container">
                            <span class="name">Số tài khoản: @item.Account</span>
                        </div>
                        <div class="content-container">
                            <span class="name">Số tiền trong ví: </span>
                            <span class="txt">@item.Money.ToString("##,##0")</span>
                        </div>
                        @if (OrderChina.Common.Utils.CheckRole((string)Session["UserType"], (int)UserType.Accounting))
                        {
                            <div>
                                <a href="@Url.Action("AdditionWallet", "Wallet", new { id = item.Id, cmd = "add" })" rel='tooltip' title="Thêm tiền" class='btn btn-info btn-xs btn-addition'><i class="fa fa-plus"></i></a>
                                <a href="@Url.Action("AdditionWallet", "Wallet", new { id = item.Id, cmd = "sub" })" rel='tooltip' title='Trừ tiền' class='btn btn-info btn-xs btn-subtract'><i class="fa fa-minus"></i></a>
                            </div>
                        }
                    </li>
                }
            </ul>

            <div class="col-sm-12">
                <hr>
            </div>
            <ul class="nav nav-tabs">
                @if (Utils.CheckRole((string)Session["UserType"], (int)UserType.Client, false))
                {
                    <li class="active"><a href="#history" data-toggle="tab">Lịch sử</a></li>
                    <li><a href="#sent" data-toggle="tab"> Chuyển khoản</a></li>
                    <li><a href="#info" data-toggle="tab">Nạp trực tiếp</a></li>
                }
                else
                {
                    <li class="active"><a href="#history" data-toggle="tab">Lịch sử</a></li>

                }
            </ul>
            <div class="tab-content">
                <div class="tab-pane" id="sent" style="margin-left:15px;margin-bottom:20px">
                    <p style="font-size:14px">
                        <br /><b> Hình thức thanh toán.</b>

                        <br />

                        BẠN ĐẶT HÀNG XONG SẼ CÓ MÃ ĐƠN HÀNG, VUI LÒNG THANH TOÁN 100% GIÁ TRỊ ĐƠN HÀNG BẰNG 1 TRONG 2 CÁCH SAU:
                        <br />
                        1. ĐẾN NỘP TIỀN TRỰC TIẾP TẠI VĂN PHÒNG
                        <br />
                        ĐỊA CHỈ : SỐ NHÀ 18 NGÕ 47 NGUYỄN KHẢ TRẠC, MAI DỊCH, CẦU GIẤY, HÀ NỘI
                        <br />
                        HOTLINE : 0167 236 3002 (DUNG) NẾU BẠN KHÔNG TÌM ĐƯỢC NHÀ ^^
                        <br />
                        2. CHUYỂN KHOẢN NGÂN HÀNG QUA 1 TRONG 2 TÀI KHOẢN SAU
                        <br />
                        <br />
                        1. Vietcombank
                        <br />
                        Số tài khoản : 0491000047763
                        <br />
                        Chủ TK        : Trần Thị Hồng Vân
                        <br />
                        Ngân hàng   : Vietcombank chi nhánh Thăng Long
                        <br />
                        <br />

                        2. Viettinbank
                        <br />
                        Số tài khoản : 711A59830641
                        <br />
                        Chủ TK        : Nguyễn Phương Dung
                        <br />
                        Ngân hàng   : Viettinbank chi nhánh Thái Hà
                        <br /><br />
                        Khi chuyển khoản vui lòng ghi nội dung chuyển tiền là : Tên + thanh toán cho mã đơn hàng nào
                        <br />
                    </p>
                </div>
                <div class="tab-pane active " id="history">
                    <table class="table table-bordered table-striped" style="font-size: 10.5px">
                        <thead>
                            <tr>
                                <th class='text-center'>Ví</th>
                                <th class='text-center'>Số tiền cập nhật</th>
                                <th class='text-center'>Loại cập nhật</th>
                                <th class='text-center'>Lý do</th>
                                <th class='text-center'>Diễn giải</th>
                                <th class="text-center">Người cập nhật</th>
                                <th class='text-center'>Ngày</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.WalletHistorys)
                            {
                                <tr>
                                    <td class='text-center'>
                                        @Html.DisplayFor(modelItem => item.Currency)
                                    </td>
                                    <td class='text-center'>
                                        @item.Money.ToString("##,##0")
                                    </td>
                                    <td class='text-center'>
                                        @item.getUpdateTypeText()
                                    </td>
                                    <td class='text-center'>
                                        @Html.TextAreaFor(modelItem => item.Reason, new { @readonly = true })
                                    </td>
                                     <td class='text-center'>
                                        <div>@item.Note</div>
                                    </td>
                                    <td class='text-center'>
                                        <div>@ViewBag.DicUser[item.User_Update]</div>
                                    </td>
                                    <td class='text-center'>
                                        @item.LastUpdate.ToString("dd/MM/yyyy HH:mm:ss")
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <br />
                    Page @(Model.WalletHistorys.PageCount < Model.WalletHistorys.PageNumber ? 0 : Model.WalletHistorys.PageNumber) of @Model.WalletHistorys.PageCount
                    @Html.PagedListPager(Model.WalletHistorys, page => Url.Action("Index", new { id = ViewBag.phone, page }))
                </div>

            </div>
        </div>
    </div>
    <div class="modal fade"
         id="myModal"
         tabindex="-1"
         role="dialog"
         aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <!-- empty -->
        </div>
    </div>
</section>

@section Scripts {
    <script>
        $(document).ready(function () {

            $('.btn-create').click(function (e) {


                e.preventDefault();

                var $modal = $('#myModal');
                var $modalDialog = $('.modal-dialog');
                var href = $(this).prop('href');

                // không cho phép tắt modal khi click bên ngoài modal
                var option = { backdrop: 'static' };

                // kiểm tra (logic, điều kiện...)

                // load modal
                $modalDialog.load(href, function () {
                    $modal.modal(option, 'show');
                });
            });
            $('.btn-addition').click(function (e) {


                e.preventDefault();

                var $modal = $('#myModal');
                var $modalDialog = $('.modal-dialog');
                var href = $(this).prop('href');

                // không cho phép tắt modal khi click bên ngoài modal
                var option = { backdrop: 'static' };

                // kiểm tra (logic, điều kiện...)

                // load modal
                $modalDialog.load(href, function () {
                    $modal.modal(option, 'show');
                });
            });
            $('.btn-subtract').click(function (e) {


                e.preventDefault();

                var $modal = $('#myModal');
                var $modalDialog = $('.modal-dialog');
                var href = $(this).prop('href');

                // không cho phép tắt modal khi click bên ngoài modal
                var option = { backdrop: 'static' };

                // kiểm tra (logic, điều kiện...)

                // load modal
                $modalDialog.load(href, function () {
                    $modal.modal(option, 'show');
                });
            });
        }); // document ready

    </script>
}

OrderChina/Views/Wallet/ListClient.cshtml
@using OrderChina.Models
@using PagedList.Mvc
@using OrderChina.Common
@model PagedList.IPagedList<OrderChina.Models.UserProfile>
@if (ViewData["message"] != null)
{
    <script>
        alert(ViewData["message"]);
    </script>
}
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<section @*class='container'*@ style='padding: 20px;'>
    <div class='row'>

        @Html.Partial("_AsideMenuPartial", new ViewDataDictionary { { "walletmanage", true } })
        @*@Html.Partial("_LayoutUser", new ViewDataDictionary { { "walletmanage", true } })*@

        <div class="col-md-9 order-content">
            <div class='row'>
                <h3 class='text-center'>DANH SÁCH NGƯỜI SỬ DỤNG</h3>

                <p>
                    @using (Html.BeginForm("ListClient", "Wallet", FormMethod.Get))
                    {
                        <div class='col-md-2' style="padding-left: inherit">
                            <input class="form-control btn-flat" placeholder="Số điện thoại"
                                    data-toggle="tooltip" rel="tooltip" autofocus="autofocus"
                                    name="userName" value="@ViewBag.CurrentUserName" type="text">
                        </div>

                        <div class='col-md-2' style="padding-left: inherit">
                            <input class="form-control btn-flat" placeholder="Mã Khách Hàng"
                                   data-toggle="tooltip" rel="tooltip" autofocus="autofocus"
                                   name="customerCode" value="@ViewBag.CurrentCustomercode" type="text">
                        </div>

                        <div class="col-xs-3 input-text">
                            <button name="submit" type="submit" class="btn btn-primary">
                                <i class="fa fa-filter"></i>
                            </button>
                        </div>

                    }
                </p>
                <div class="col-sm-12">
                    <hr>
                </div>
                <div class="table-responsive" style="width: 100%">

                    <table class="table table-bordered table-striped" style="font-size: 10.5px">
                        <thead>
                            <tr>
                                <th class='text-center'>Mã khách hàng</th>
                                <th class='text-center'>Họ tên</th>
                                <th class='text-center'>Số điện thoại</th>
                                <th class="text-center">Ngày sinh</th>
                                <th class="text-center">Số tài khoản</th>
                                <th class='text-center'>Thao tác</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td class='text-center'>
                                        @Html.DisplayFor(modelItem => item.customercode)
                                    </td>
                                    <td class='text-center'>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td class='text-center'>
                                        @Html.DisplayFor(modelItem => item.Phone)
                                    </td>

                                    <td class='text-center'>
                                        @if (!string.IsNullOrEmpty(item.Phone))
                                        {
                                            @item.Birthday.ToString("dd/MM/yyyy")
                                        }
                                    </td>
                                    <td class='text-center'>
                                        @Html.DisplayFor(modelItem => item.Account)
                                    </td>
                                    <td class='text-center'>
                                        <a rel='tooltip' title="Ví điện tử" href=@Url.Action("Index", "Wallet", new { id = item.Phone }) class="btn btn-xs btn-primary">
                                            <i class="fa fa-money"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <br />
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                @Html.PagedListPager(Model, page => Url.Action("ListClient", new { page, userType = ViewBag.CurrentUserType, userName = ViewBag.CurrentUserName, customerCode = ViewBag.CurrentCustomercode }))
            </div>
        </div>
    </div>
    <div class="modal fade"
         id="myModal"
         tabindex="-1"
         role="dialog"
         aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <!-- empty -->
        </div>
    </div>
</section>

OrderChina/Views/Wallet/_AdditionWallet.cshtml
@{
    ViewBag.Title = "AdditionWallet";
}
@using OrderChina.Common
@using OrderChina.Models
@model OrderChina.Models.AdditionModel
@Scripts.Render("~/bundles/jqueryval")


@using (Html.BeginForm("AdditionWallet", "Wallet", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel">@(ViewBag.isaddition ? "Cộng tiền cho ví" : "Trừ tiền cho ví")</h4>
        </div>
        <div class="modal-body">
            <div class="form-group row" style="width: 100%;font-size: 14px">
                @Html.HiddenFor(m => m.walletid)
                <div class="col-sm-5">
                    <label>Số tiền</label>
                    @Html.TextBoxFor(m => m.money, new { @class = "form-control btn-flat", autofocus = "autofocus", placeholder = "Nhập số tiền" })
                </div>
                <div class="col-sm-5">
                    <label>Lý do</label>
                    @Html.TextBoxFor(m => m.reason, new { @class = "form-control btn-flat", placeholder = "Nhập lý do" })
                    @Html.ValidationMessageFor(m => m.reason)
                </div>
                @if (Utils.CheckRole(ViewBag.UserType, (int)UserType.Client, false))
                {
                    <div class="col-sm-5">
                        <label>Hình thức TT</label>
                        @Html.DropDownListFor(m => m.BankName, (IEnumerable<SelectListItem>) ViewBag.ListBankName, "--Chọn Hình thức thanh toán--", new {@class = "form-control flat", style = "display: inline;"})
                    </div>
                }
                
            </div>
            <div class="modal-footer">
                @if (ViewBag.isaddition == true)
                {
                    <button type="submit" id="btnUpdate" value="addition" name="cmd" class="btn btn-primary">Cập nhật</button>
                }
                else
                {
                    <button type="submit" value="subtract" id="btnSave" name="cmd" class="btn btn-primary">Cập nhật</button>
                }
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
}