OrderChina/Controllers/ReportsController.cs
using OrderChina.Models;
using OrderChina.Temp_Reports.SurviveEarlyMonth;
using QuantEdge.Worker.ReportManager.Utils;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Telerik.Reporting;

namespace OrderChina.Controllers
{
    public class ReportsController : Controller
    {
        //
        // GET: /Reports/

        public ActionResult Index()
        {
            var model = new ReportsModel();
            ViewBag.ListReportType = GetListReportType();
            ViewBag.ListMonths = GetListMonths();
            return View(model);
        }

        [HttpPost]
        public ActionResult GetReports(ReportsModel model)
        {
            try
            {
                if (string.IsNullOrEmpty(model.ReportType))
                {
                    return Json(new { success = false, msg = "Yêu cầu chọn báo cáo" });
                }
                if (model.ReportType == ReportType.SurviveEarlyMonth.ToString())
                {
                    if (model.Month <= 0)
                    {
                        return Json(new { success = false, msg = "Chưa chọn tháng" });
                    }
                    var report = new SurviveEarlyMonth(model.Month);
                    var renderingResult = ExportFileUtils.GetByteForReportOutputType_RenderReport(report, ExportType.Xlsx);

                    return Json(new { success = true, BytesData = Convert.ToBase64String(renderingResult.DocumentBytes), ReportName = renderingResult.DocumentName, Type = renderingResult.MimeType, Extension = renderingResult.Extension });
                }

            }
            catch (Exception ex)
            {
                return Json(new { success = false, msg = ex.ToString() });
            }

            return Json(new { success = false, msg = "Xuất báo cáo lỗi" });

        }


        private SelectList GetListReportType()
        {
            var list = new List<object>();
            foreach (FieldInfo fieldInfo in typeof(ReportType).GetFields())
            {
                if (fieldInfo.FieldType.Name != "ReportType")
                    continue;
                var attribute = Attribute.GetCustomAttribute(fieldInfo,
                    typeof(DisplayAttribute)) as DisplayAttribute;

                list.Add(attribute != null
                    ? new { name = fieldInfo.Name, display = attribute.Name }
                    : new { name = fieldInfo.Name, display = fieldInfo.Name });
            }

            return new SelectList(list, "name", "display");
        }

        private SelectList GetListMonths()
        {
            var dDur = new List<object>();
            dDur.Add(new { value = 1, display = "Tháng một" });
            dDur.Add(new { value = 2, display = "Tháng hai" });
            dDur.Add(new { value = 3, display = "Tháng ba" });
            dDur.Add(new { value = 4, display = "Tháng bốn" });
            dDur.Add(new { value = 5, display = "Tháng năm" });
            dDur.Add(new { value = 6, display = "Tháng sáu" });
            dDur.Add(new { value = 7, display = "Tháng bảy" });
            dDur.Add(new { value = 8, display = "Tháng tám" });
            dDur.Add(new { value = 9, display = "Tháng chín" });
            dDur.Add(new { value = 10, display = "Tháng mười" });
            dDur.Add(new { value = 11, display = "Tháng 11" });
            dDur.Add(new { value = 12, display = "Tháng 12" });

            return new SelectList(dDur, "value", "display", DateTime.Now.Month);
        }

    }
}

OrderChina/Views/Reports/Index.cshtml
@using OrderChina.Models;
@using System.Web.Script.Serialization;

@{
    ViewBag.Title = "Index";
    Layout = null;
}
@model ReportsModel
@*@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")*@
@Scripts.Render("~/bundles/bootbox")
@Scripts.Render("~/bundles/filesaver")


<div class="modal-content">
    <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Báo cáo</h4>
    </div>
    <div class="modal-body">
        <div class="form-group row" style="width: 100%;font-size: 14px">
            <div class="col-sm-4">
                @Html.LabelFor(m => m.ReportType)
                @Html.DropDownListFor(m => m.ReportType, (IEnumerable<SelectListItem>)ViewBag.ListReportType, "--Chọn báo cáo--", new { id = "reportType", @class = "form-control flat", style = "width: 300px;display: inline;" })
                @Html.ValidationMessageFor(m => m.ReportType)
            </div>
            <div class="col-sm-4" style="display:none">
                @Html.LabelFor(m => m.Month)
                @Html.DropDownListFor(m => m.Month, (IEnumerable<SelectListItem>)ViewBag.ListMonths, "--Chọn tháng--", new { @class = "form-control flat", style = "width: 300px;display: inline;" })
                @Html.ValidationMessageFor(m => m.Month)
            </div>
        </div>
        <div class="modal-footer">
            <button id="btnReport" class="btn btn-primary">Xuất báo cáo</button>
            <button type="button" class="btn btn-red" data-dismiss="modal">Đóng</button>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('select#reportType').change(function () {
            var reportType = $(this).val();

            if (reportType === "SurviveEarlyMonth") {
                //ẩn hiện ở đây
                $("#Month").parent().show();
            }
        });
       
        $('#btnReport').click(function () {
            console.log("alo");
            var data = {
                ReportType: $("select#reportType").val(),
                Month: $("#Month").val()
            };
            var model = { model: data };
            $.ajax({
                url: "@Url.Action("GetReports", "Reports")",
                type: 'POST',
                data: JSON.stringify(model),
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    if (data.success) {
                        var fileContent = base64ToArrayBuffer(data.BytesData);
                        var file = new Blob([fileContent], { type: data.Type });

                        var today = new Date();
                        var dd = today.getDate();
                        var mm = today.getMonth() + 1; //January is 0!
                        var yyyy = today.getFullYear();
                        var hour = today.getHours();
                        var mi = today.getMinutes();
                        var ss = today.getSeconds();
                        if (dd < 10) {
                            dd = '0' + dd
                        }
                        if (mm < 10) {
                            mm = '0' + mm
                        }
                        if (mi < 10) {
                            mi = '0' + mi
                        }
                        if (ss < 10) {
                            ss = '0' + ss
                        }

                        //YYMMDD_HHmmss

                        var name = data.ReportName + "_" + yyyy + mm + dd + "_" + hour + mi + ss + "." + data.Extension;
                        saveAs(file, name);
                    } else {
                        bootbox.alert(data.msg);
                    }
                },
                error: function () {
                    bootbox.alert("Lỗi");
                }
            });
        });
    });
    var base64String = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    function base64DecodeLookup() {
        var coreArrayBuffer = new window.ArrayBuffer(256);
        var base64DecodeLookupTable = new Uint8Array(coreArrayBuffer);
        for (var i = 0; i < base64String.length; i++) {
            base64DecodeLookupTable[base64String[i].charCodeAt(0)] = i;
        }
        return base64DecodeLookupTable;
    };
    function base64ToArrayBuffer(base64) {
        var base64Decode = base64DecodeLookup();
        var bufferLength = base64.length * 0.75,
            len = base64.length, i, p = 0,
            encoded1, encoded2, encoded3, encoded4;
        if (base64[base64.length - 1] === "=") {
            bufferLength--;
            if (base64[base64.length - 2] === "=") {
                bufferLength--;
            }
        }

        var arraybuffer = new window.ArrayBuffer(bufferLength),
            bytes = new Uint8Array(arraybuffer);
        for (i = 0; i < len; i += 4) {
            encoded1 = base64Decode[base64.charCodeAt(i)];
            encoded2 = base64Decode[base64.charCodeAt(i + 1)];
            encoded3 = base64Decode[base64.charCodeAt(i + 2)];
            encoded4 = base64Decode[base64.charCodeAt(i + 3)];

            bytes[p++] = (encoded1 << 2) | (encoded2 >> 4);
            bytes[p++] = ((encoded2 & 15) << 4) | (encoded3 >> 2);
            bytes[p++] = ((encoded3 & 3) << 6) | (encoded4 & 63);
        }
        return arraybuffer;
    };
</script>