OrderChina/Controllers/NewsController.cs
using OrderChina.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using OrderChina.Filters;

namespace OrderChina.Controllers
{
    
    public class NewsController : Controller
    {
        DBContext db = new DBContext();

        public ActionResult Index(int? page)
        {
            int pageSize = 8;
            int pageNum = (page ?? 1);
            List<New> lisnew = new List<New>();
            lisnew = (from a in db.News select a).ToList();
            //var sp = from a in db.News select a;
            //
            return View(lisnew.ToPagedList(pageNum, pageSize));
        }
        public ActionResult DetailNews(int id)
        {

            var news = from a in db.News where a.IDNews == id select a;
            return View(news);
        }
        [Authorize]  
        [InitializeSimpleMembership]
        public ActionResult ManageNews(int? page)
        {
            int pageSize = 20;
            int pageNum = (page ?? 1);
            List<New> lisnew = new List<New>();
            lisnew = (from a in db.News select a).ToList();
            return View(lisnew.ToPagedList(pageNum, pageSize));
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(New model, FormCollection collection)
        {        
            if (ModelState.IsValid)
            {
                string title = collection["Title"];
                string titlebig = collection["Titlebig"];
                string content = collection["NewsContent"];
                string img = collection["Img"];
                model.Title = title;
                model.Titlebig = titlebig;
                model.NewsContent = content;
                model.Img = img;
                db.News.Add(model);
                db.SaveChanges();
            }
            return RedirectToAction("ManageNews");
        }
        #region Edit
        public ActionResult Edit(int id)
        {
            return View(db.News.Find(id));
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, FormCollection collection)
        {
            
            if (ModelState.IsValid)
            {
                var news = db.News.First(m => m.IDNews == id);
                string title = collection["Title"];
                string titlebig = collection["Titlebig"];
                string content = collection["NewsContent"];
                string img = collection["Img"];
                news.Title = title;
                news.Titlebig = titlebig;
                news.NewsContent = content;
                news.Img = img;
                UpdateModel(news);
                db.SaveChanges();
            }
            return RedirectToAction("ManageNews");
        }
        
        #endregion
        #region Delete
        public ActionResult Delete(int id)
        {
            var product = db.News.First(p => p.IDNews == id);
            db.News.Remove(product);
            db.SaveChanges();
            return RedirectToAction("ManageNews");

        }
        #endregion
       
    }
}

OrderChina/Views/News/Create.cshtml
@{

}
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
<script src="~/Content/ckeditor_asp/_Samples/ckeditor/ckeditor.js"></script>
<script src="~/Content/ckfinder/ckfinder.js"></script>
<script type="text/javascript">
    function BrowseServer() {
        var finder = new CKFinder();
        finder.selectActionFunction = SetFileField;
        finder.popup();
    }
    function SetFileField(fileUrl) {
        document.getElementById('Img').value = fileUrl;
    }
    var ckeditor;
    function createEditor(languageCode, id) {
        var editor = CKEDITOR.replace(id, { language: languageCode })
    }
    $(function () { createEditor('vi', 'editor') })
</script>
@using (Html.BeginForm("Create", "News", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="editor-label">
        Tiêu đề tin tức:
    </div>
    <div class="editor-field">
        @Html.TextBox("Title", null, new { @class = "form-control" })
    </div>

    <div class="editor-label">
        Mô tả cơ bản:
    </div>
    <div class="editor-field">
        @Html.TextBox("Titlebig", null, new { @class = "form-control" })
    </div>

    <div class="editor-label">
        Nội dung chi tiết:
    </div>
    <div class="editor-field">
        @Html.TextArea("NewsContent", null, new { id = "editor" })

    </div>

    <div class="editor-label">
        Hình ảnh mô tả:
    </div>
    <div class="editor-field">
        @Html.TextBox("Img", null, new { @class = "form-control" })
        <button class="btn btn-success" type="button" value="" onclick="BrowseServer();" style="width:150px">Chọn Ảnh ...</button>
        
    </div>

    <p align="center">
        <button type="submit" value="" class="btn btn-primary" >Thêm</button>
    </p>

}

OrderChina/Views/News/DetailNews.cshtml
@{
    ViewBag.Title = "Tin tức";
}
@using OrderChina.Models;
@model IEnumerable<OrderChina.Models.News>
<div style="font-family: Arial, sans-serif ; padding: 50px 10px 20px 20px; background-color:white " class="col-xs-12">
    <div style="background-color: #f5f5f5;height:40px"><p style="padding:8px 10px 10px 12px;font-size:13pt"><a href="#" style="color:#03aaff">Tin tức</a> / Tin tức về công ty</p> </div>
    @foreach(var sp in Model)
    {
        <div style="padding:15px 0px 15px 20px"><h2 style="font-size:20px; color:#03aaff">@sp.Title</h2></div>
        <div>
           @Html.Raw(sp.NewsContent)
        </div>
    }   
</div>

OrderChina/Views/News/Edit.cshtml
@{

}
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
<script src="~/Content/ckeditor_asp/_Samples/ckeditor/ckeditor.js"></script>
<script src="~/Content/ckfinder/ckfinder.js"></script>
<script type="text/javascript">
    function BrowseServer() {
        var finder = new CKFinder();
        finder.selectActionFunction = SetFileField;
        finder.popup();
    }
    function SetFileField(fileUrl) {
        document.getElementById('Img').value = fileUrl;
    }
    var ckeditor;
    function createEditor(languageCode, id) {
        var editor = CKEDITOR.replace(id, { language: languageCode })
    }
    $(function () { createEditor('vi', 'editor') })
</script>
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<style>
    .news {
        width: 70%;
        margin: auto 5%;
    }
</style>
<section @*class='container'*@ style='padding: 20px;'>
    <div class="news">
        <h2>Sửa tin tức</h2>
        <div class='row'>
            @Html.Partial("_AsideMenuPartial", new ViewDataDictionary { { "Node", true } })

            <div class="col-md-9 order-content">
                <div class='row'>
                    <h3 class='text-center'>QUẢN LÍ TIN TỨC</h3>
                    <hr>
                    @using (Html.BeginForm("Edit", "News", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="editor-label">
                            Tiêu đề tin tức:
                        </div>
                        <div class="editor-field">
                            @Html.TextBox("Title", null, new { @class = "form-control" })
                        </div>

                        <div class="editor-label">
                            Mô tả cơ bản:
                        </div>
                        <div class="editor-field">
                            @Html.TextBox("Titlebig", null, new { @class = "form-control" })
                        </div>

                        <div class="editor-label">
                            Nội dung chi tiết:
                        </div>
                        <div class="editor-field">
                            @Html.TextArea("NewsContent", null, new { id = "editor" })

                        </div>

                        <div class="editor-label">
                            Hình ảnh mô tả:
                        </div>
                        <div class="editor-field">
                            @Html.TextBox("Img", null, new { @class = "form-control" })
                            <button class="btn btn-success" type="button" value="" onclick="BrowseServer();" style="width:150px">Chọn Ảnh ...</button>
                        </div>

                        <p align="center">
                            <button type="submit" value="" class="btn btn-primary">Sửa</button>
                        </p>

                    }
                </div>
            </div>
        </div>
    </div>
</section>

OrderChina/Views/News/Index.cshtml
@{
    ViewBag.Title = "Tin tức";
}
@using OrderChina.Models;
@model PagedList.IPagedList<OrderChina.Models.News>
@*@model IEnumerable<OrderChina.Models.News>*@
@using PagedList;
@using PagedList.Mvc;
<div style="font-family: Arial, sans-serif ; padding: 50px 10px 100px 20px; background-color:white "class="col-xs-12">
    <div style="background-color: #f5f5f5;height:40px"><p style="padding:8px 10px 10px 12px;font-size:13pt"><a href="#" style="color:#03aaff">Tin tức</a> / Tin tức về công ty</p> </div>
    <div style="padding:15px 0px 15px 20px"><h2 style="font-size:28px">Tin tức</h2></div>
    <div>

        @foreach (var sp in Model)
        {
            <div style="min-width: 90%; max-height: 100%; margin-left: 2%; background-color: #f5f5f5;border-radius: 10px">
                <table>
                    <tr>
                        <td rowspan="2" style="width:40%; height:200px">
                            <a href="@Url.Action("DetailNews", "News", new {id=@sp.IDNews })" style="background-color: #f5f5f5"><img src="@sp.Img" style="width:95%; height: 95%;margin-left:2%" /></a>
                        </td>
                        <td style="min-width:100%;max-height:40px"><a href="@Url.Action("DetailNews", "News", new {id=@sp.IDNews })" style="color: blue; background-color:#f5f5f5"> <p style="font-size:1em">@sp.Title</p> </a></td>
                    </tr>
                    <tr>
                        <td><p style="font-size: 1em">@sp.Titlebig</p></td>
                    </tr>

                </table>
            </div>
        }
        
    </div>
    
    <div style="float: right; padding-right: 1%">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
    </div> 
</div>

OrderChina/Views/News/ManageNews.cshtml
@model PagedList.IPagedList<OrderChina.Models.News>
@using PagedList.Mvc;

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<script>
    function Deleteconfirm() {
        if (confirm("Bạn có chắc chắn muốn xóa tin này này"))
            return true;
        else
            return false;
    }
    FocusEvent = false;
    checked = false;
</script>

<section @*class='container'*@ style='padding: 20px;'>
    <div class="news">
        <div class='row'>
            @Html.Partial("_AsideMenuPartial", new ViewDataDictionary { { "Node", true } })

            <div class="col-md-9 order-content">
                <div class='row'>
                    <h3 class='text-center'>DANH SÁCH TIN TỨC</h3>

                    <p>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
                            Tạo mới tin tức
                        </button>
                    </p>
                    <hr>

                    <div>
                        <table class="table table-bordered table-striped">
                            <tr>
                                <td>Mã tin tức</td>
                                <td>Tiêu đề</td>
                                <td>Thời gian cập nhật</td>
                                <td>Thao tác</td>
                            </tr>
                            @foreach (var news in Model)
                            {
                                <tr>
                                    <td>@news.IDNews</td>
                                    <td>@news.Title</td>
                                    <td></td>
                                    <td>
                                        <a href="@Url.Action("Edit", "News", new { id = @news.IDNews })">
                                            <i class="glyphicon glyphicon-pencil" title="Sửa"></i>
                                        </a>
                                        
                                        @Html.ActionLink("Xóa","Delete", new { id = news.IDNews }, new { @onclick = "return Deleteconfirm() ", title = "Delete",  })
                                    </td>
                                </tr>
                            }
                        </table>
                    </div>
                    <div style="float: right; padding-right: 1%">
                        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }), PagedListRenderOptions.OnlyShowFivePagesAtATime)
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Tạo mới tin tức</h4>
                    </div>
                    <div class="modal-body">
                        @Html.Partial("Create")
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>